
Q_TOKEN     = "<Q_TARGET>"
URL_TOKEN   = "<URL>"

AUTHOR_OF_THE_TWEET = "AUTHOR OF THE TWEET"
NEAR_AUTHOR_OF_THE_TWEET = "NEAR AUTHOR OF THE TWEET"
NOT_SPECIFIED = "Not Specified"

DATA_FOLDER = './data'
OUTPUT_DATA_FOLDER = '.'

MIN_POS_SAMPLES_THRESHOLD = 10
